# Generated by Django 3.2.7 on 2021-10-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_rooms',
            field=models.ManyToManyField(blank=True, related_name='active_users', to='app.ChatRoom'),
        ),
    ]
